load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
# git_repository(
#     name = "rules_idris",
#     remote = "https://github.com/BryghtWords/rules_idris.git",
#     tag = "v0.3"
# )

local_repository(
  name = "rules_idris",
  path = "/Users/davidsmith/personal/idris/rules_idris",
)

load("@rules_idris//idris:idris_repos.bzl", "loadIdrisRepositories")
loadIdrisRepositories()

load("@rules_idris//idris:idris_loader.bzl", "loadIdris")
loadIdris()
